services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.back
    ports: 
      - 3000:3000
    environment: 
      - HTTP_PORT=3000
      - MONGO_URL=url
      - JWT_SECRET=secret
      - JWT_EXPIRES=3d
    depends_on:
      mongodb
    networks:
      - backend

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  frontend:
    build: 
      context: ./
      dockerfile: ./Dockerfile.front
    ports: 
      - 80:3000
    volumes:
      - ./frontend:/app
    environment: 
      - VITE_MAIN_URL=http://localhost:3000/api
      - VITE_SERVER_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - backend

networks:
    backend:
      driver: bridge