services:      
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.back
    ports: 
      - 3000:3000
    environment: 
      - HTTP_PORT=4001
      - MONGO_URL=url
      - JWT_SECRET=secret
      - JWT_EXPIRES=3d
    networks:
      - backend

  frontend:
    build: 
      context: ./
      dockerfile: ./Dockerfile.front
    ports: 
      - 80:3000
    volumes:
      - ./frontend:/app
    environment: 
      - VITE_MAIN_URL=http://localhost:3000/api
      - VITE_SERVER_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - backend

networks:
    backend:
      driver: bridge